
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ADMIN = 27;
  public static final int PUNTO = 18;
  public static final int GUION = 8;
  public static final int PUNTOYCOMA = 6;
  public static final int DOSPUNTOS = 7;
  public static final int CADENA = 13;
  public static final int LETRA = 11;
  public static final int GUIONÑ = 9;
  public static final int DECIMAL = 14;
  public static final int OP = 16;
  public static final int DIVISION = 23;
  public static final int BAJO = 25;
  public static final int FLECHA = 5;
  public static final int ID = 12;
  public static final int COMA = 15;
  public static final int ASTERISCO = 20;
  public static final int EOF = 0;
  public static final int DOBLE = 24;
  public static final int CONJ = 10;
  public static final int DISYUNCION = 19;
  public static final int NUMERO = 17;
  public static final int error = 1;
  public static final int LLAVE_IZQ = 3;
  public static final int ENTERO = 2;
  public static final int LLAVE_DER = 4;
  public static final int AMPERSAND = 26;
  public static final int INTER = 22;
  public static final int MAS = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "FLECHA",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "GUION",
  "GUIONÑ",
  "CONJ",
  "LETRA",
  "ID",
  "CADENA",
  "DECIMAL",
  "COMA",
  "OP",
  "NUMERO",
  "PUNTO",
  "DISYUNCION",
  "ASTERISCO",
  "MAS",
  "INTER",
  "DIVISION",
  "DOBLE",
  "BAJO",
  "AMPERSAND",
  "ADMIN"
  };
}

